apiVersion: v2
name: kagent-crds
description: CRDs for kagent
type: application
version: ${VERSION}
dependencies:
  - name: kmcp-crds
    version: ${KMCP_VERSION}
    repository: oci://ghcr.io/kagent-dev/kmcp/helm
    condition: kmcp.enabled
