apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "querydoc.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "querydoc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "querydoc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.openai.apiKey }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
      labels:
        {{- include "querydoc.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "querydoc.serviceAccountName" . }}
      containers:
        - name: querydoc
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "querydoc.fullname" . }}
            {{- if .Values.openai.apiKey }}
            - secretRef:
                name: {{ include "querydoc.fullname" . }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
