apiVersion: v2
name: kagent
description: A Helm chart for kagent, built with Google ADK
type: application
version: ${VERSION}
dependencies:
  - name: kagent-tools
    version: 0.0.12
    repository: oci://ghcr.io/kagent-dev/tools/helm
    condition: kagent-tools.enabled
  - name: grafana-mcp
    version: ${VERSION}
    repository: file://../tools/grafana-mcp
    condition: tools.grafana-mcp.enabled, agents.observability-agent.enabled
  - name: querydoc
    version: ${VERSION}
    repository: file://../tools/querydoc
    condition: tools.querydoc.enabled
  - name: k8s-agent
    version: ${VERSION}
    repository: file://../agents/k8s
    condition: agents.k8s-agent.enabled
  - name: kgateway-agent
    version: ${VERSION}
    repository: file://../agents/kgateway
    condition: agents.kgateway-agent.enabled
  - name: istio-agent
    version: ${VERSION}
    repository: file://../agents/istio
    condition: agents.istio-agent.enabled
  - name: promql-agent
    version: ${VERSION}
    repository: file://../agents/promql
    condition: agents.promql-agent.enabled
  - name: observability-agent
    version: ${VERSION}
    repository: file://../agents/observability
    condition: agents.observability-agent.enabled
  - name: argo-rollouts-agent
    version: ${VERSION}
    repository: file://../agents/argo-rollouts
    condition: agents.argo-rollouts-agent.enabled
  - name: helm-agent
    version: ${VERSION}
    repository: file://../agents/helm
    condition: agents.helm-agent.enabled
  - name: cilium-policy-agent
    version: ${VERSION}
    repository: file://../agents/cilium-policy
    condition: agents.cilium-policy-agent.enabled
  - name: cilium-manager-agent
    version: ${VERSION}
    repository: file://../agents/cilium-manager
    condition: agents.cilium-manager-agent.enabled
  - name: cilium-debug-agent
    version: ${VERSION}
    repository: file://../agents/cilium-debug
    condition: agents.cilium-debug-agent.enabled
